# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "TestFlight Build and Push"
  lane :beta do
    # Build jsbundle
    Dir.chdir "../.." do
      sh "react-native bundle --platform ios --dev false --entry-file index.ios.js --bundle-output ios/main.jsbundle --assets-dest ios"
    end

    # Icon
    appicon(appicon_image_file: '../assets/appicon/teacup.png',
      appicon_path: 'crypto_react/Images.xcassets',
      appicon_devices: [:iphone, :ios_marketing])

    # Build app
    increment_build_number(xcodeproj: "crypto_react.xcodeproj")
    match(type: "appstore", git_url:"git@github.com:bpevangelista/fastlane_certificates.git")
    build_app(scheme: "crypto_react", configuration: "Release", output_directory: "builds")
    upload_to_testflight
  end

  desc "Development Build"
  lane :dev do
    # Icon
    appicon(appicon_image_file: '../assets/appicon/teacup.png',
      appicon_path: 'crypto_react/Images.xcassets',
      appicon_devices: [:iphone, :ios_marketing])

    # Build app
    Dir.chdir "../.." do
      sh "react-native run-ios --scheme crypto_react --configuration Debug --simulator=\"iPhone 7\""
    end
  end

  lane :icons do
    appicon(appicon_image_file: '../assets/appicon/teacup.png',
      appicon_path: 'crypto_react/Images.xcassets',
      appicon_devices: [:iphone, :ios_marketing])
  end
end
